# Numpy Assignment

#### 1) Write a function so that the columns of the output matrix are powers of the input vector.
#### The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

#### HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.

In [15]:
import numpy as np

def vd_matrix(array , n , increasing = False):
    if not increasing:
        output = np.array([x**(n-1-i) for x in array for i in range(n)]).reshape(array.size , n)
    else:
        output = np.array([x**i for x in array for i in range (n)]).reshape(array.size , n)
        
    return output
        
array = np.array([1,2,3,4,5])
col_size = 4
print('Decreasing \n')
print(vd_matrix(array , col_size ))
print('\n')
print('Increasing \n')
print(vd_matrix(array , col_size , True))

Decreasing 

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]


Increasing 

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]]


#### 2) Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average ofthe given sequence is defined as follows: The moving average sequence has n-k+1 elements as shown below. The moving averages with k=4 of a ten-value sequence (n=10) is shown below
#### i 1 2 3 4 5 6 7 8 9 10
#### ===== == == == == == == == == == ==
#### Input 10 20 30 40 50 60 70 80 90 100
#### y1 25 = (10+20+30+40)/4
#### y2 35 = (20+30+40+50)/4
#### y3 45 = (30+40+50+60)/4
#### y4 55 = (40+50+60+70)/4
#### y5 65 = (50+60+70+80)/4
#### y6 75 = (60+70+80+90)/4
#### y7 85 = (70+80+90+100)/4
#### Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question : Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [34]:
def moving_avg(array , n):
    a = np.cumsum(array , dtype = float)
    a[n:] = a[n:] - a[:-n]
    return (a[n - 1:])/n

a = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
n = 3
np.array(moving_avg(a , n).round(2))

array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])